#pragma checksum "C:\Users\User-PC\Desktop\Web-App_1\WebApplication1\WebApplication1\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3139642a3426d379fe1b07cc242bcee885c898f7"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Index), @"mvc.1.0.view", @"/Views/Home/Index.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/Index.cshtml", typeof(AspNetCore.Views_Home_Index))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "C:\Users\User-PC\Desktop\Web-App_1\WebApplication1\WebApplication1\Views\_ViewImports.cshtml"
using WebApplication1;

#line default
#line hidden
#line 2 "C:\Users\User-PC\Desktop\Web-App_1\WebApplication1\WebApplication1\Views\_ViewImports.cshtml"
using WebApplication1.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"3139642a3426d379fe1b07cc242bcee885c898f7", @"/Views/Home/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"729efaa87342638aecfe1a972ce9f9f8dff55b4c", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("deleteIcon"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/Images/deleteImage.png"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("title", new global::Microsoft.AspNetCore.Html.HtmlString("Delete Image"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 4, true);
            WriteLiteral("\r\n\r\n");
            EndContext();
#line 3 "C:\Users\User-PC\Desktop\Web-App_1\WebApplication1\WebApplication1\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Index";

#line default
#line hidden
            BeginContext(61, 312, true);
            WriteLiteral(@"<div class=""jumbotron"">
    <h2>User Guide : </h2>
    <h4>Images can be downloaded by clicking on them </h4>
    <h4>To Delete an image click on the delete icon on that image </h4>
   

    <h4>If you haven't uploaded any images yet use the ""select files"" button and upload your images </h4>

</div>

");
            EndContext();
#line 17 "C:\Users\User-PC\Desktop\Web-App_1\WebApplication1\WebApplication1\Views\Home\Index.cshtml"
 using (Html.BeginForm("UploadAsync", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

#line default
#line hidden
            BeginContext(482, 201, true);
            WriteLiteral("    <div class=\"fileUpload btn btn-primary\">\r\n        <span>Select Files</span><input type=\"file\" id=\"file\" name=\"selectFiles\" class=\"upload\" onchange=\"DisplayFilesToUpload()\" multiple />\r\n    </div>\r\n");
            EndContext();
            BeginContext(685, 32, true);
            WriteLiteral("    <p id=\"FilesToUpload\"></p>\r\n");
            EndContext();
#line 24 "C:\Users\User-PC\Desktop\Web-App_1\WebApplication1\WebApplication1\Views\Home\Index.cshtml"
}

#line default
#line hidden
            BeginContext(720, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 26 "C:\Users\User-PC\Desktop\Web-App_1\WebApplication1\WebApplication1\Views\Home\Index.cshtml"
 if (Model != null && Model.Count > 0)
{
    foreach (var item in Model)
    {

#line default
#line hidden
            BeginContext(805, 48, true);
            WriteLiteral("        <div class=\"imageBlock\">\r\n            <a");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 853, "\"", 865, 1);
#line 31 "C:\Users\User-PC\Desktop\Web-App_1\WebApplication1\WebApplication1\Views\Home\Index.cshtml"
WriteAttributeValue("", 860, item, 860, 5, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(866, 35, true);
            WriteLiteral(" target=\"_blank\"><img class=\"thumb\"");
            EndContext();
            BeginWriteAttribute("src", " src=\"", 901, "\"", 912, 1);
#line 31 "C:\Users\User-PC\Desktop\Web-App_1\WebApplication1\WebApplication1\Views\Home\Index.cshtml"
WriteAttributeValue("", 907, item, 907, 5, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(913, 63, true);
            WriteLiteral(" alt=\"images\" /></a><br />\r\n            <div class=\"deleteDiv\">");
            EndContext();
            BeginContext(976, 110, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "8af3e26e8ea24f6b849c88f00bcad5f3", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "onclick", 3, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            AddHtmlAttributeValue("", 1061, "deleteImage(\'", 1061, 13, true);
#line 32 "C:\Users\User-PC\Desktop\Web-App_1\WebApplication1\WebApplication1\Views\Home\Index.cshtml"
AddHtmlAttributeValue("", 1074, item, 1074, 5, false);

#line default
#line hidden
            AddHtmlAttributeValue("", 1079, "\');", 1079, 3, true);
            EndAddHtmlAttributeValues(__tagHelperExecutionContext);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(1086, 24, true);
            WriteLiteral("</div>\r\n        </div>\r\n");
            EndContext();
#line 34 "C:\Users\User-PC\Desktop\Web-App_1\WebApplication1\WebApplication1\Views\Home\Index.cshtml"
    }

    using (Html.BeginForm("DeleteAll", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

#line default
#line hidden
            BeginContext(1233, 139, true);
            WriteLiteral("        <div class=\"fileUpload btn btn-danger\"><span>Delete All Files</span><input type=\"submit\" name=\"deleteAll\" class=\"upload\" /></div>\r\n");
            EndContext();
#line 39 "C:\Users\User-PC\Desktop\Web-App_1\WebApplication1\WebApplication1\Views\Home\Index.cshtml"
    }
}

#line default
#line hidden
            BeginContext(1382, 1152, true);
            WriteLiteral(@"<script>
    //Calls async Task<ActionResult> DeleteImage(string name) in the HomeController and Refreshes the page
    function deleteImage(item) {
        var url = ""/Home/DeleteImage"";
        $.post(url, { Name: item }, function (data) {
            window.location.href = ""/Home/Index"";
        });
    }

    //Lists the file name and size for all files to be uploaded by updating the <p id=""FilesToUpload""></p> control
    function DisplayFilesToUpload() {
        var element = document.getElementById(""file"");
        var html = """";

        html = ""<h3>Image(s) to Upload</h3>""
        for (var i = 0; i < element.files.length; i++) {
            html += ""<strong>"" + (i + 1) + ""</strong>. File: "";
            var file = element.files[i];
            if ('name' in file) { html += file.name + "" (""; }
            if ('size' in file) { html += ""size: "" + file.size + "" bytes)<br>""; }
        }

        html += ""<div class='fileUpload btn btn-primary'><span>Upload</span><input type='submit' ");
            WriteLiteral("class=\'upload\' value=\'Upload\'/></div>\"\r\n        document.getElementById(\"FilesToUpload\").innerHTML = html;\r\n    }\r\n\r\n</script>\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
